### ISSUE TITLE
Crash in app

### ISSUE THREAD

**Issue by lgyjg** [TaoMonkey/ViewPagerTest#2]
01-06 12:09:30.482  8133  8133 D AndroidRuntime: Shutting down VM
01-06 12:09:30.484  8133  8133 E AndroidRuntime: FATAL EXCEPTION: main
01-06 12:09:30.484  8133  8133 E AndroidRuntime: Process: com.example.taoguo.pageviewtest, PID: 8133
01-06 12:09:30.484  8133  8133 E AndroidRuntime: java.lang.RuntimeException: com.example.taoguo.pageviewtest.MainActivity@1cc10e0 must implement OnFragmentInteractionListener
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at com.example.taoguo.pageviewtest.BlankFragment1.onAttach(BlankFragment1.java:83)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1231)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1085)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:976)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:95)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1116)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1642)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6153)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6153)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6153)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6153)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6153)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:701)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.View.measure(View.java:19757)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2299)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1371)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1620)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1259)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6341)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:619)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6174)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
01-06 12:09:30.484  8133  8133 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by TaoMonkey** [comment]
是华为手机对log级别做了改动，权限放开了这些异常信息就都有了。。。。
